"""
Django settings for CampusLab project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lee el archivo .env de la raíz del proyecto, si existe, y deja sus valores
# disponibles como variables de entorno. Lo que ya venga del sistema o de Docker
# tiene prioridad: el .env nunca pisa una variable que ya estaba definida.
load_dotenv(BASE_DIR / ".env")


def env(name, default=None):
    return os.getenv(name, default)


def env_bool(name, default=False):
    return env(name, str(int(default))).strip().lower() in {"1", "true", "yes", "on"}


SECRET_KEY = env("SECRET_KEY", "cambia-esta-clave-en-desarrollo")
JWT_SECRET_KEY = env("JWT_SECRET_KEY", "clave-jwt-desarrollo-super-segura-12345")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_MINUTES = int(env("ACCESS_TOKEN_MINUTES", "60"))
REFRESH_TOKEN_DAYS = int(env("REFRESH_TOKEN_DAYS", "7"))

DEBUG = env_bool("DEBUG", True)
ALLOWED_HOSTS = [
    host.strip()
    for host in env("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pwghyht!z=brc-%b4lehc&*y62ywaybb)f(hhuz8ovcwh=azu4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

EXTERNAL_APPS = [
    "ninja",
]


# Una app por cada cosa distinta que resuelve el sistema. El orden de la lista
# no cambia el funcionamiento, pero conviene escribirlas de la que no depende de
# nadie a la que depende de todas: es el mismo orden en el que se construyen.
LOCAL_APPS = [
    "apps.accounts.apps.AccountsConfig",
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CampusLab.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CampusLab.wsgi.application"

sqlite_path = Path(env("SQLITE_PATH", BASE_DIR / "data" / "db.sqlite3"))
sqlite_path.parent.mkdir(parents=True, exist_ok=True)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": sqlite_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "es-ar"
TIME_ZONE = "America/Argentina/Buenos_Aires"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
 
MEDIA_URL = "/media/" # es para los que suben los usuarios: en este caso las imágenes y los videos de cada proyecto.
MEDIA_ROOT = BASE_DIR / "media"

# le dice a Django cuál es el modelo de usuario, y tiene que estar antes de la primera migración: si Django ya creó las tablas con su usuario por defecto, cambiarlo después obliga a borrar la base y arrancar de nuevo.
AUTH_USER_MODEL = "accounts.User" # Paso 12
 
# En desarrollo los emails se imprimen en la consola del servidor: se ve el
# envio sin configurar un servidor de correo. En produccion se cambia el
# backend por SMTP con las credenciales reales, via variables de entorno.
EMAIL_BACKEND = env("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend") # esta primera etapa todavía no usa pero deja listo.
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "no-responder@bancodeproyectos.edu.ar")
 
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/" # es para los archivos que trae el proyecto (por ejemplo el CSS del admin) Paso 12 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
